notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: pN32PQVgx9V1LF3J03zfJPauOFdsjotehGzdJnNotgnVQjIYnkYXYAF+e6fm04Hp2YtC/AoSuefuGXLALmtDX9qJuM3zO1nHccSqqwZI3zT+hgBmPQNx9rLtbqv3gmB+DR7Ol9PjqA7AuYQKSjiqW1xGAmUHYh4qJV4fgueFieBnc5dmCoQwp7dmGP7vYY8VmLBsrzH9Ek06IFT5a4fAZ9xp9/96al0AZU5EMsyouGcfii4OHYCUQnz2flDIwjqPhUcWhhU8nWNs/b2kLgYDinGlWWV5g/+QK5vgNnBostT0XooHf+G2J4ti83YiDZwHq1s2YWHAfwT1tPMcz31LYrr/pL0sJkBVph7fCnS0CyIsWpFdaeBiToA1kySWny5XA28kaeuVv4a0mjY2KhHSZXhL4YrXfwFRV7kBbH2wQq+2gqrF+HX6CDDNpLrEWT5e/pun1O/TOjBw6uBWtQzyjMcs/Lruy9I4mkNGVg5m1yQJhSuboTZBh/g6vUU6nHJx+wGPLn5hZZ6NxjPQtf/KmAPUNtmpCWtlEuy75HlZNdkQhCo3KYcn/RxN9dGZjRR2SADpriYVTv1vp4iON57vXoFGoYW5KDmDjaxjc2benJlzEWujplS4X4vhBlRJLKYp2DIav76OMSmyasnPDGAuFXYARcu5OBH3rTHUXm3d/sA=
  api_key:
    secure: npDMNyMHzSRKNQa/kRCLU3h8Jxuip0kLJPzFL340Kfyie7sjczo5mb+7Sb+lACYPx6apu9U9YC7Cx/zOETBpkf9JWa3i0jPW/0W24eFl0VdGCibdmSyjWQhj8umkc00mSf29RD1d/PveKFvuK2HzpRnsfzB9OjSEQKsnb4kfFwfzyjT7HrRMlbOFKSX3NP4ku+I4w791Y1rub4E0WIt32rSAN1BlK5C2/1gATcQZ4OD33LwX18DNVOf4z5MciM9YWrygpTSDb1n8PI517Ar437wzYJQDCzKrurVtZid0AWcLLr4uhn21tZgZqYx2OGRa9Smcs1VbAHmosGQxcZNwJE43qcDL20tRIr2E1V8irIRfYjM/SidURkpY1EbIHteWukEgR7bktctZFODQY0sR6zsRK3CFouYy0nv9dujLIWp7oOxJcrR6+qO2ImiDLqO7io/ujzR8dLuMB/k/iu9KIs0YxwUAWsOxA/rBG9Ut+Ij1gzIVKeJpDMWJDlse6ELKZPcp0PPCaDzJ3ylnqpuGmDios6qY8+ZtpFFY9kmqXaW4IQoH4psb3Sn3K0e5XJ321tZ2hsLNG8wrx5THmUupd5Kzo2rjIWD2PH4mi4+ub6OOvzBAZG4z/cOTJY3ZqV+A6BYuPaIgHzXW6IRcysLh9VxKeco81vFkObk5eMyz7VI=
  on:
    tags: true
